services:
  odoo:
    environment:
      - PYTHONDONTWRITEBYTECODE=True
      - LOCAL_USER_ID=$UID
      - RUNNING_ENV=$ENV
      - MARABUNTA_MODE=demo
      - DB_HOST=$PGHOST
      - DB_NAME=$PGDATABASE
      - DB_USER=$PGUSER
      - DB_PASS=$PGPASSWORD
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGUSER=$PGUSER
      - PGPASSWORD=$PGPASSWORD
      - ADDONS_PATH=/odoo/links,/odoo/local-src,/odoo/src/odoo/addons,/odoo/src/addons,/odoo/external-src/account-payment,/odoo/external-src/bank-payment,/odoo/external-src/currency,/odoo/external-src/server-tools,/odoo/external-src/l10n-brazil,/odoo/external-src/account-financial-reporting,/odoo/external-src/server-ux,/odoo/external-src/reporting-engine,/odoo/external-src/account-invoicing,/odoo/external-src/stock-logistics-workflow
    hostname: ${ENV}-${COMPOSE_PROJECT_NAME}
    labels:
      docky.main.service: true
      docky.user: odoo
    volumes:
      - ./odoo:/odoo
      - ./data/addons:/data/odoo/addons
      - ./data/filestore:/data/odoo/filestore
      - ./data/sessions:/data/odoo/sessions
version: '3.7'
volumes:
  py3o_tmp: null
